name: build test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
    test:
      strategy:
        matrix:
          os: [ubuntu-latest]
      runs-on: ${{matrix.os}}
      steps:
        - uses: actions/checkout@v4
        - uses: goto-bus-stop/setup-zig@v2
          with:
            version: 0.11.0
        - run: zig build test
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: goto-bus-stop/setup-zig@v2
          with:
            version: 0.11.0
        - run: zig fmt --check src/**/*.zig